# The list of rules can be found at
# https://realm.github.io/SwiftLint/rule-directory.html

excluded:
  - Carthage
  - Pods
  - ".build"
  - "CoverDropCore/.build"
  - "CoverDropUserInterface/.build"
  - Packages
  - SourcePackages

disabled_rules:
  - force_cast
  - cyclomatic_complexity
  - nesting
  - function_parameter_count
  - multiple_closures_with_trailing_closure
  - closure_body_length
  - function_body_length
  - type_body_length
  - file_length
  - block_based_kvo
  - notification_center_detachment
  - switch_case_alignment
  - todo

line_length:
  warning: 120
  error: 120
  ignores_function_declarations: true
  ignores_urls: true
