// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PublicEncryptionKey } from "./PublicEncryptionKey";

export type U2JMessage = { id: bigint, userPk: PublicEncryptionKey, message: string, receivedAt: string, normalExpiry: string, customExpiry: string | null, read: boolean, };
