import {
  EuiButtonIcon,
  EuiFlexGroup,
  EuiFlexItem,
  useEuiTheme,
} from "@elastic/eui";
import { UserStatus } from "../model/bindings/UserStatus";
import { palette } from "../styles/palette";

export const ChatHeader = ({
  userAlias: userAlias,
  userAutogeneratedName: userAutogeneratedName,
  currentUserStatus,
  userDescription,
  setIsMuteModalVisible: setIsMuteModalVisible,
  setIsEditModalVisible: setIsEditModalVisible,
}: {
  userAlias: string | null;
  userAutogeneratedName: string;
  currentUserStatus: UserStatus;
  userDescription: string;
  setIsMuteModalVisible: (isVisible: boolean) => void;
  setIsEditModalVisible: (isVisible: boolean) => void;
}) => {
  const headerName = userAlias
    ? `${userAlias} (${userAutogeneratedName})`
    : userAutogeneratedName;

  const { euiTheme } = useEuiTheme();
  const { font, size } = euiTheme;

  return (
    <EuiFlexItem
      grow={false}
      style={{
        fontSize: `calc(${size.base} + 2)`,
        fontWeight: font.weight,
        borderBottom: `1px solid ${palette("chat-header-border-color")}`,
        paddingBottom: size.s,
        paddingTop: size.l,
        paddingLeft: size.base,
        background: palette("chat-header-background"),
        zIndex: 100, // prevent chat from scrolling over the header
        position: "sticky",
        top: 0,
      }}
    >
      <EuiFlexGroup direction="row" gutterSize="s">
        <EuiFlexItem
          style={{
            fontSize: "18px",
            fontWeight: "bold",
          }}
          grow={true}
        >
          {headerName}
        </EuiFlexItem>
        <EuiFlexItem grow={false}>
          <EuiButtonIcon
            display="base"
            iconType="pencil"
            aria-label="info"
            color="primary"
            onClick={() => setIsEditModalVisible(true)}
            title="Update user alias"
          />
        </EuiFlexItem>
        <EuiFlexItem grow={false}>
          {currentUserStatus === "ACTIVE" ? (
            <EuiButtonIcon
              display="base"
              iconType="bellSlash"
              aria-label="info"
              color="primary"
              onClick={() => setIsMuteModalVisible(true)}
              title="Mute source"
              style={{ marginRight: "12px" }}
            />
          ) : (
            <EuiButtonIcon
              display="base"
              iconType="bell"
              aria-label="info"
              color="primary"
              onClick={() => setIsMuteModalVisible(true)}
              title="Unmute source"
              style={{ marginRight: "12px" }}
            />
          )}
        </EuiFlexItem>
      </EuiFlexGroup>
      {userDescription ? (
        <EuiFlexGroup
          direction="row"
          gutterSize="s"
          style={{
            fontSize: "15px",
            paddingTop: "4px",
            marginRight: "80px",
          }}
        >
          <EuiFlexItem grow={true}>{userDescription}</EuiFlexItem>
        </EuiFlexGroup>
      ) : null}
    </EuiFlexItem>
  );
};
