import type { Meta, StoryObj } from "@storybook/react-vite";

import { ChatHeader } from "./ChatHeader";

const meta = {
  component: ChatHeader,
} satisfies Meta<typeof ChatHeader>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {
  args: {
    userAlias: "User alias",
    userAutogeneratedName: "bountiful harvest",
    currentUserStatus: "ACTIVE",
    userDescription:
      "This user contacted us after reading the story about Evil Corporation",
    showMuteModal: () => {},
    showEditModal: () => {},
    markAsUnread: () => {},
    showCopyToClipboardModal: () => {},
  },
};
