import { EuiConfirmModal } from "@elastic/eui";
import { UserStatus } from "../model/bindings/UserStatus";
import { sizes } from "../styles/sizes";

export const ToggleMuteModal = (
  currentUserStatus: UserStatus,
  userAutogeneratedName: string,
  closeModal: () => void,
  handleMuteUser: (e: React.MouseEvent<HTMLButtonElement, MouseEvent>) => void,
) => {
  const title =
    currentUserStatus === "ACTIVE" ? "Mute source" : "Unmute source";
  const text =
    currentUserStatus === "ACTIVE"
      ? `Muted sources will appear in the "Muted" tab. They
        will still be able to send you messages, but you will not receive
        notifications for them.`
      : `Do you want to unmute this source?`;

  return (
    <EuiConfirmModal
      style={{ width: sizes.toggleMuteModal.width }}
      title={
        <div>
          {title} <i>{userAutogeneratedName}</i>?
        </div>
      }
      onCancel={closeModal}
      onConfirm={handleMuteUser}
      cancelButtonText="Cancel"
      confirmButtonText={title}
      buttonColor="primary"
    >
      <p>{text}</p>
    </EuiConfirmModal>
  );
};
