CREATE TABLE user_dead_drops (
    id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL,
    data       BYTEA NOT NULL,
    cert       BYTEA NOT NULL
);

CREATE TABLE journalist_dead_drops (
    id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL,
    data       BYTEA NOT NULL,
    cert       BYTEA NOT NULL
);
