// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Message =
  | {
      type: "userToJournalistMessage";
      id: bigint;
      userPk: string;
      message: string;
      receivedAt: string;
      read: boolean;
    }
  | {
      type: "journalistToUserMessage";
      id: bigint;
      userPk: string;
      message: string;
      sentAt: string;
      isSent: boolean;
    };
