// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * This outcome is returned when a vault is successfully unlocked but includes warnings
 */
export type OpenVaultOutcome = { "type": "openedOffline" } | { "type": "openedOnline", orgPksMissingInVault: Array<string>, orgPksMissingInApi: Array<string>, };
