// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SentinelLogEntry = { timestamp: string, level: number, target: string, message: string, };
