// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserStatus } from "./UserStatus";

export type User = { "type": "User", userPk: string, status: UserStatus, displayName: string, alias: string | null, description: string | null, markedAsUnread: boolean, };
