[package]
name = "integration-test-queries"
version = "0.1.0"
edition = "2021"

[dependencies]

sqlx = { workspace = true, features = [
    "runtime-tokio-rustls",
    "postgres",
    "json",
    "chrono",
] }
serde.workspace = true
serde_json.workspace = true
