# The endpoint for receiving data from the API
coverdrop.apiBaseUrl="https://secure-messaging-api-staging.guardianapis.com"
# The endpoint for sending data to Kinesis via the CDN endpoint
coverdrop.fastlyBaseUrl="https://secure-messaging-msg-staging.guardianapis.com"
# Comma-separated list of trusted organization keys
coverdrop.trustedOrgPks="6b1733544db3201c805c9a08ec87e6e9c1d60aec55d16e82fb1fb4cebf529bb4,ae7b71f1188b471098c996aef1b41b9813caa8aaff7fb8af5aa5be99ea43e161"
