#!/usr/bin/env bash

if ! git diff --cached --name-only | grep -q "^journalist-client/"; then
  echo "No changes to journalist-client. Skipping pre-commit hook."
  exit 0
fi

echo "Linting journalist-client..."
cd journalist-client
npx lint-staged
