CREATE TABLE users (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mailbox_path TEXT NOT NULL,
    password TEXT NOT NULL
);

CREATE TABLE journalists (
    id TEXT PRIMARY KEY,
    phone_number TEXT NOT NULL,
    pin TEXT NOT NULL
);

CREATE TABLE user_to_journalist_messages (
    user_id INTEGER NOT NULL REFERENCES users(id),
    journalist_id TEXT NOT NULL REFERENCES journalists(id),
    sent_at TIMESTAMPTZ NOT NULL,
    received_at TIMESTAMPTZ,
    message TEXT NOT NULL
);

CREATE TABLE journalist_to_user_messages (
    journalist_id TEXT NOT NULL REFERENCES journalists(id),
    user_id INTEGER NOT NULL REFERENCES users(id),
    sent_at TIMESTAMPTZ NOT NULL,
    received_at TIMESTAMPTZ,
    message TEXT NOT NULL
);

CREATE TABLE processed_dead_drops (
    dead_drop_id INTEGER NOT NULL,
    processed_at TIMESTAMPTZ NOT NULL
);
CREATE INDEX ON processed_dead_drops (dead_drop_id);