// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AlertLevel } from "./AlertLevel";

export type AlertPayload = { level: AlertLevel; message: string };
