// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BackupAttemptFailureReason =
  | "VAULT_TOO_LARGE"
  | "INSUFFICIENT_RECOVERY_CONTACTS_SELECTED"
  | "INSUFFICIENT_RECOVERY_CONTACTS_WITH_VALID_KEYS"
  | "S3"
  | "UNKNOWN";
