// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BackupChecks = {
  isBackupVolumeMounted: boolean;
  isEncrypted: boolean;
  maybeExistingBackups: Array<string> | null;
};
