// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EventType =
  | "outbound_queue_length"
  | "dead_drops_remaining"
  | "journalist_keys_rotated"
  | "automated_backup"
  | "alert";
