// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SentinelIdentity } from "./SentinelIdentity";

/**
 * Represents the content of a message in a group chat to be stored in the vault and displayed in the UI.
 * It includes variants that are never directly sent via the DS (UserAdded, UserRemoved). These two variants
 * are the user-facing representations of MLS commit messages.
 * Stored as JSON in the database via manual sqlx trait implementations.
 */
export type GroupMessageContent =
  | { Text: string }
  | { IsTyping: boolean }
  | { UsersAdded: Array<SentinelIdentity> }
  | { UsersRemoved: Array<SentinelIdentity> }
  | { GroupNameChanged: string }
  | { GroupDescriptionChanged: string }
  | { GroupInfo: { display_name: string; description: string } };
