// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PublicEncryptionKey } from "./PublicEncryptionKey";

export type J2UMessage = {
  id: bigint;
  userPk: PublicEncryptionKey;
  message: string;
  isSent: boolean;
  sentAt: string;
  normalExpiry: string;
  customExpiry: string | null;
};
