// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type JournalistStatus =
  | "VISIBLE"
  | "HIDDEN_FROM_UI"
  | "HIDDEN_FROM_RESPONSE";
