// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LogEntry = {
  id: bigint | null;
  timestamp: string;
  level: string;
  target: string;
  message: string;
  sessionId: bigint | null;
};
