// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { J2UMessage } from "./J2UMessage";
import type { U2JMessage } from "./U2JMessage";

export type Message =
  | ({ type: "userToJournalistMessage" } & U2JMessage)
  | ({ type: "journalistToUserMessage" } & J2UMessage);
