// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserStatus } from "./UserStatus";

export type Message =
  | {
      type: "userToJournalistMessage";
      id: bigint;
      from: string;
      fromDisplayName: string;
      message: string;
      receivedAt: string;
      read: boolean;
      userStatus: UserStatus;
      userAlias: string | null;
      userDescription: string | null;
    }
  | {
      type: "journalistToUserMessage";
      id: bigint;
      to: string;
      toDisplayName: string;
      message: string;
      sentAt: string;
      isSent: boolean;
      userStatus: UserStatus;
      userAlias: string | null;
      userDescription: string | null;
    };
