// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A type alias for the tag at the beginning of the serialized message that indicates the intended
 * recipient (or the fact it's a cover message).
 */
export type RecipientTag = string;
