// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SentinelIdentity } from "./SentinelIdentity";

export type SentinelProfile = { id: SentinelIdentity; display_name: string };
