// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UntrustedOrganizationPublicKeyFamily = {
  org_pk: unknown;
  covernodes: unknown;
  journalists: unknown;
  backup: unknown;
};
