// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Epoch } from "./Epoch";
import type { JournalistIdentity } from "./JournalistIdentity";
import type { JournalistProfile } from "./JournalistProfile";
import type { UntrustedOrganizationPublicKeyFamilyList } from "./UntrustedOrganizationPublicKeyFamilyList";

/**
 * Not a huge fan of this structure - we should perhaps separate out the keys and the journalist info
 * there's potentially a lot of data in the journalist info that doesn't change very much which makes
 * pulling them both down together a bit wasteful.
 */
export type UntrustedKeysAndJournalistProfiles = {
  journalist_profiles: Array<JournalistProfile>;
  default_journalist_id: JournalistIdentity | null;
  keys: UntrustedOrganizationPublicKeyFamilyList;
  max_epoch: Epoch;
};
