// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Information about the open vault that the frontend cares about
 */
export type VaultState = {
  type: "VaultState";
  id: string;
  path: string;
  isSoftLocked: boolean;
};
