import { ReactElement, useEffect, useState } from "react";

import {
  EuiPageTemplate,
  EuiPageTemplateProps,
  EuiGlobalToastList,
  useEuiTheme,
} from "@elastic/eui";
import { ChatsSideBar } from "./components/ChatsSideBar";
import { OpenVault } from "./views/OpenVault";
import { getVaultState } from "./commands/vaults";
import { VaultState } from "./model/bindings/VaultState";
import { Chat } from "./components/Chat";
import { Toast } from "@elastic/eui/src/components/toast/global_toast_list";
import { useErrorStore } from "./state/errors";
import { useMessageStore } from "./state/messages";
import { applyPalette, ColorMode } from "./styles/palette";
import { useUserStore } from "./state/users";
import { getChats, getUsers } from "./commands/chats";

const App = ({
  panelled,
  bottomBorder = true,
  offset,
  grow,
}: {
  content?: ReactElement;
  sidebar?: ReactElement;
  panelled?: EuiPageTemplateProps["panelled"];
  bottomBorder?: EuiPageTemplateProps["bottomBorder"];
  // For fullscreen only
  offset?: EuiPageTemplateProps["offset"];
  grow?: EuiPageTemplateProps["grow"];
}) => {
  const { colorMode } = useEuiTheme();

  useEffect(() => {
    applyPalette(colorMode.toLowerCase() as ColorMode);
  }, [colorMode]);

  const [vaultState, setVaultState] = useState<VaultState | null>(null);
  const [currentUserReplyKey, setCurrentUserReplyKey] = useState<string | null>(
    null,
  );

  const errorsState = useErrorStore();

  const toasts = errorsState.errors.map((e) => ({
    id: e.id,
    title: "Error",
    color: "danger" as const,
    iconType: "warning",
    text: <p>{e.message}</p>,
  }));

  const messageStore = useMessageStore();
  const userStore = useUserStore();

  // Fetch initial messages and users and set interval to refresh them
  // every 5 seconds
  const fetchUsersAndChats = async () => {
    const [users, messages] = await Promise.all([getUsers(), getChats()]);
    userStore.setUsers(users);
    messageStore.setMessages(messages);
  };
  useEffect(() => {
    // return early if there isn't an open vault
    if (vaultState === null) {
      return;
    }

    fetchUsersAndChats();
    const intervalId = setInterval(() => {
      fetchUsersAndChats();
    }, 5000);

    return () => clearInterval(intervalId);
  }, [vaultState]);

  const userInfo = userStore.getUserInfo();

  useEffect(() => {
    getVaultState().then((s) => {
      setVaultState(s);
    });
  }, []);

  useEffect(() => {
    const unreadMessageHasArrivedForSelectedUser =
      currentUserReplyKey &&
      messageStore.messages.some(
        (msg) =>
          msg.userPk === currentUserReplyKey &&
          msg.type === "userToJournalistMessage" &&
          !msg.read,
      );
    if (unreadMessageHasArrivedForSelectedUser) {
      setCurrentUserReplyKey(null);
    }
  }, [messageStore.messages.length]);

  return (
    <div>
      {vaultState === null ? (
        <OpenVault setVaultState={setVaultState} />
      ) : (
        <EuiPageTemplate
          panelled={panelled}
          bottomBorder={bottomBorder}
          grow={grow}
          offset={offset}
        >
          <EuiPageTemplate.Sidebar
            style={{
              position: "sticky",
              top: "0",
              height: "100vh",
              overflowY: "auto",
            }}
            minWidth={325}
          >
            <ChatsSideBar
              userAlias={vaultState.id}
              currentUserReplyKey={currentUserReplyKey}
              setChat={setCurrentUserReplyKey}
            />
          </EuiPageTemplate.Sidebar>
          {currentUserReplyKey ? (
            <Chat
              messages={messageStore.messages}
              userReplyKey={currentUserReplyKey}
              userAutogeneratedName={userInfo[currentUserReplyKey].displayName}
              setCurrentUserReplyKey={setCurrentUserReplyKey}
              currentUserStatus={userInfo[currentUserReplyKey].status}
              userAlias={userInfo[currentUserReplyKey].alias}
              userDescription={userInfo[currentUserReplyKey].description}
              fetchUsersAndChats={fetchUsersAndChats}
            />
          ) : null}
        </EuiPageTemplate>
      )}

      <EuiGlobalToastList
        toasts={toasts}
        dismissToast={(t: Toast) => {
          errorsState.removeError(t.id);
        }}
        toastLifeTimeMs={6000}
      />
    </div>
  );
};

export default App;
